version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/learn_spanish
# permissions: read-all|write-all
hooks:
  # ApplicationStop:
  #  - location: scripts/application_stop.sh
  #    timeout: 6
  #    runas: ec2-user
# DownloadBundle:
  BeforeInstall:
   - location: scripts/change_permissions.sh
     timeout: 6
     runas: ec2-user
# Install:
  AfterInstall:
   - location: scripts/after_install.sh
     timeout: 1000
     runas: ec2-user
  ApplicationStart:
   - location: scripts/application_start.sh
     timeout: 3000
     runas: ec2-user